on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 5
        package:
          - bitwuzla-cxx

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam pin add . --no-action

      - run: opam install ${{ matrix.package }} --deps-only --with-test

      - run: opam exec -- dune build --only-packages ${{ matrix.package }} @install

      - run: opam exec -- dune build --only-packages ${{ matrix.package }} @runtest
